### ISSUE TITLE
Mousewheel on Add Node/FX dropdown accidentally adds many nodes

### ISSUE THREAD

**Issue by tannerhelland** [miorsoft/Site#3]
An animated GIF may be the easiest way to show this:

![photo_modular](https://user-images.githubusercontent.com/1930029/41923890-e4282982-7925-11e8-8a32-6a4335cfb6ae.gif)

Probably best if the actual "**add** node" action is restricted to mouse **clicks**, only?

**Comment by miorsoft** [comment]
This seems an issue of vbRichclient vbWidgets cwDropDownList.cls
https://github.com/vbRichClient/vbWidgets/blob/master/cwDropDownList.cls
On mousewheel rotation , event Click is raised.
I still haven't understand how to fix

More precisely it's related to (sub)Class cwVList (of cwDropDownList): https://github.com/vbRichClient/vbWidgets/blob/master/cwVList.cls

On mousewheel on DropDownList there's     VList.ListIndex = NewIndex
and in
Public Property Let ListIndex(ByVal NewValue As Long)
    .....
    ..... 
    RaiseEvent Click      <<<------- This raises VList_Click *
    W.RaiseBubblingEvent Me, "Click"
End Property
and
*
Private Sub VList_Click()
     .....
     .....
     RaiseEvent Click <<<------- This raises click event of DropDownList
End Sub

.... really a mess !

**Comment by tannerhelland** [comment]
Good detective work!

Without modifying the cwVList + cwDropDownList directly, the only workarounds I can think of are probably tedious for users.  For example, you could add a new "add node" button, which the user has to click *after* closing the list.  But extra clicks are usually not good for usability.  :disappointed:

But maybe this would be necessary to solve the mousewheel problem anyway - for example, if the user uses the mousewheel to change the selected effect, and the `Click()` event *doesn't* fire, how would the user add the node?  I guess they would have to open the dropdown, and click the name *again*... which isn't very intuitive.

I'm not sure the best solution.  :frowning_face:

**Comment by miorsoft** [comment]
At the moment, I resolved it roughly
I modified cwDropDownList (since I already use a custom version of it)


I added to variables
```
Public OkToUseMouseWheel As Boolean
Private Wheeling As Boolean
```
```
Private Sub Class_Initialize()
OkToUseMouseWheel = True
```
in FX-Selector  `.OkToUseMouseWheel = False` (in ResizeMode and FileName-Prefix/Postfix it's `True` by default)

and used these 2 variables this way:

```
Private Sub W_MouseWheel(ByVal MouseKeys As Long, ByVal Rotation As Long, ByVal LineOffset As Long, ByVal xAbs As Single, ByVal yAbs As Single)
    If DropDown.PopupWidget Is Nothing And VList.ListCount > 0 And W.Enabled Then
        Wheeling = True
        Dim NewIndex: NewIndex = VList.ListIndex + LineOffset
        If NewIndex < 0 Then NewIndex = 0 Else If NewIndex >= VList.ListCount Then NewIndex = VList.ListCount - 1
        VList.ListIndex = NewIndex
        Wheeling = False
    End If
End Sub
```

```
Private Sub VList_Click()
   .....

   ' If DoRaise Then
   '      RaiseEvent Click
   '      W.RaiseBubblingEvent Me, "Click"
   ' End If

    If OkToUseMouseWheel Then
        If DoRaise Then
            RaiseEvent Click
            W.RaiseBubblingEvent Me, "Click"
        End If
    Else
        If DoRaise Then
            If Not (Wheeling) Then
                RaiseEvent Click
                W.RaiseBubblingEvent Me, "Click"
            End If
        End If
    End If
End Sub
```

At the moment seems to work 


>  But maybe this would be necessary to solve the mousewheel problem anyway - for example, if the user uses the mousewheel to change the selected effect, and the Click() event doesn't fire, how would the user add the node? I guess they would have to open the dropdown, and click the name again... which isn't very intuitive.

Yes, and at the moment, (with this fix), even if mousewheel do not fire Click event, when user  open the dropdown, _and click the name again, nothing happens._

This was an Old issue: (always of cwDropDownList)

- Click a name, and a NodeFX will be added.
- Click again the Same Name and nothing happens (Click event not fired)

Anyway, I think I will update PhotoModularFX only with this fix (Do not add nodeFX on mousewheel)

**Comment by vbRichClient** [comment]
Did you already read my comments reexre?

If disabling the MouseWheel is all you want, you can do it on the outside 
(in your User-Code) by setting:
MyComboList.Widget.ImplementsWheelMessages = False 

That's all.

Olaf

**Comment by miorsoft** [comment]
> Did you already read my comments reexre?
> 
> If disabling the MouseWheel is all you want, you can do it on the outside
> (in your User-Code) by setting:
> MyComboList.Widget.ImplementsWheelMessages = False
> 
> That's all.
> 
> Olaf

Thanks
I'll use ImplementsWheelMessages = False. (more straightforward)

By the way,
Why when I click an item the Click event is fired,
and if I click again the Same Item (already highlighted/selected), the Click event is _not_ fired ?

( If I would add 2 "BLUR"-Nodes, for example, I would click 2 times the same Item (Blur), but only the first time works (Click fired) )

**Comment by vbRichClient** [comment]
Yes, that's due to the cwDropDownList being developed primarily as DataBound-Control.
(where one shouldn't raise Events, when the "bound state" was not changed)...

If you need that badly in your DropDownList-scenario, then you can (also in UserCode) simply 
add an additional EventListener (on the DropDownLists internal VList.Widget).

Private WithEvents VListW As cWidgetBase 'somewhere at Class-Level

'shortly after instancing your DropDownList-Widget:
Set VListW = Combo1.VList.Widget 'assign and add a reference to the internal VList-Base

'now you can sink e.g. VListW_MouseUp and react there instead of your Combo_Click
Private Sub VListW_MouseUp(Button As Integer, Shift As Integer, ByVal x As Single, ByVal y As Single)
  Debug.Print Combo1.DataSource.FieldValue(0)
End Sub

HTH

Olaf

**Comment by miorsoft** [comment]
Thank you very much!!!
I used:
`Set cmbFxSelectorVLIST = cmbFxSelector.VList`   (  without `.Widget` )
`Private Sub cmbFxSelectorVLIST_MouseUpClick()`
Works perfectly !

**Comment by miorsoft** [comment]
Updated https://miorsoft.github.io/Site/PhotoModularFX/
